### ISSUE TITLE
端口显示Hello World!，但是用不了

### ISSUE THREAD

**Issue by CatCars** [xkrfer/claude-in-slack-api#1]
![1](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/bc9bf5be-1fe9-43a6-bd83-a885ef7457d8)
![2](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/c34729af-526e-41b9-9ccb-56fc1746d7ca)
![3](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/b2ea5380-5981-412b-ba56-672c88d19600)
![4](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/c93b843c-a60a-408f-bcee-614c337594e5)
![5](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/678f3921-83c7-43e7-8d87-276aa6f5eb1e)
![6](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/40f030b8-7771-43d0-8e59-d3fd1fc30e4a)
![7](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/9891c1b5-8fc3-4942-a2f8-987f7fd3dd6e)
![8](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/dab56932-3e33-4363-9913-d30c32a6b34f)
![9](https://github.com/xkrfer/claude-in-slack-api/assets/44657929/9e7889d9-0117-46b9-a105-b8945bf41e06)

救救孩子吧，孩子已经看傻了。
穷举了一遍实在不知道是哪里出了问题了=-=。

**Comment by CatCars** [comment]
里的工作区是正常的，我刚测试了极端的问题。没限制

**Comment by xkrfer** [comment]
@CatCars 可以手动调试一下：
我以curl为例子，你可以用postman测试一下：
```bash
curl --location 'http://127.0.0.1:9000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 你的token' \
--data '{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "测试"
    }
  ],
  "max_tokens": 100,
  "temperature": 1,
  "stream": true
}'
```

**Comment by xkrfer** [comment]
@CatCars  如果接口是能请求成功的，但在https://web.chatboxapp.xyz上使用不了，确认下填入的url是不是https的，因为https的域名下不允许发起非https的请求

**Comment by CatCars** [comment]
> @CatCars可以手动测试下： 我以curl为例子，你可以用postman测试下：
> 
> ```shell
> curl --location 'http://127.0.0.1:9000/v1/chat/completions' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer 你的token' \
> --data '{
>   "model": "gpt-3.5-turbo",
>   "messages": [
>     {
>       "role": "user",
>       "content": "测试"
>     }
>   ],
>   "max_tokens": 100,
>   "temperature": 1,
>   "stream": true
> }'
> ```

响应是
{
    "statusCode": 500,
    "message": "Internal server error"
}

**Comment by CatCars** [comment]
重新建app已经可以了
